config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :ads do
    member do
      get 'clone'
    end
  end

root 'ads#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable and :registerable,
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy, :clone]

  def clone
    @ad = Ad.find(params[:id])
  end

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :description, :price, :address, :city, :image)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
<% if @ad.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

  <ul>
    <% @ad.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.cktext_area :description %>
</div>
<div class="field">
  <%= f.label :price %><br>
  <%= f.text_field :price %>
</div>
<div class="field">
  <%= f.label :address %><br>
  <%= f.text_field :address %>
</div>
<div class="field">
  <%= f.label :city %><br>
  <%= f.text_field :city %>
</div>
<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/ads/clone.html.erb
<h1> Clone</h1>


<%= form_for @ad, url: '/ads', method: :post do |f|%>

<% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :description %><br>
	<%= f.cktext_area :description %>
</div>
<div class="field">
	<%= f.label :price %><br>
	<%= f.text_field :price %>
</div>
<div class="field">
	<%= f.label :address %><br>
	<%= f.text_field :address %>
</div>
<div class="field">
	<%= f.label :city %><br>
	<%= f.text_field :city %>
</div>
<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>
<div class="actions">
	<%= f.submit %>
</div>

<% end %>
<%= link_to 'Back', ads_path %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<p id='notice'><%= notice %></p>
<% if admin_signed_in? %>
<%= link_to "New Ad", '/ads/new', class: 'btn btn-success'  %>
<% end %>
<center> <h1>280,351 ads in London on the UK's</h1> </center>
<hr>

<% @ads.each do |ad| %>
<div class="col-md-2">
  <%= image_tag ad.image, class: " img-responsive" %>
</div>
<div class="col-md-10">
  <div class="col-md-12">
    <% if admin_signed_in? %>
    <%= link_to "Edit Ad", "/ads/#{ad.id}/edit", class: 'btn btn-info btn-xs'  %>
    <%= link_to "Clone Ad", "/ads/#{ad.id}/clone", class: 'btn btn-warning btn-xs'  %>
    <%= link_to "Delete Ad", "/ads/#{ad.id}", class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' }%>
    <% end %>
    <h4><%= link_to ad.title, ad %></h4>
  </div>  
  <div class="col-md-6">
    <strong>Address: </strong><%= ad.address %>, <%= ad.city %>
  </div>
  <div class="col-md-6">
    <strong>Price: </strong><%= ad.price %>
  </div>
</div>
<div class="col-md-12">
  <hr>
</div>
<% end %>

app/views/ads/new.html.erb
<h1>New Ad</h1>

<%= render 'form' %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<div class="col-md-3">
 <%= image_tag @ad.image, class: " img-responsive" %>
</div>

<div class="col-md-9">
  <div class="col-md-12"> 
    <hr>
    <h4>
      <%= @ad.title  %>
    </h4>
  </div>
  <div class="col-md-6"> 
    <strong>Price:</strong>
    <%= @ad.price %>
  </div>
  <div class="col-md-6"> 
    <strong>Address:</strong>
    <%= @ad.address %>, <%= @ad.city %>
  </div>
  <div class="col-md-12"> 
    <hr>
    <strong>Description:</strong>
    <%= simple_format @ad.description %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlatRental</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/ads">
          FlatRental
        </a>
      </div>
      
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to "Log out", destroy_admin_session_url, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to "Sign in", new_admin_session_url %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>